title: "Richard Pearsall"
description: "Cloud Engineering | Automation | Linux | Infrastructure-as-Code"
remote_theme: just-the-docs/just-the-docs

# 1. Enable Mermaid in the theme
mermaid:
  enabled: true
