title: "Richard Pearsall"
description: "Cloud Engineering | Automation | Linux | Infrastructure-as-Code"
remote_theme: just-the-docs/just-the-docs

# Add this section for Mermaid support
mermaid:
  enabled: true
